apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
      - name: devops-container
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: devops-service
spec:
  type: NodePort             # <- Changed from ClusterIP to NodePort
  selector:
    app: devops-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080         # <- Jenkins will curl this port

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: devops-service
            port:
              number: 80
