apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: devops-app
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: devops-service
spec:
  type: ClusterIP
  selector:
    app: my-app
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: micro123.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: devops-service
            port:
              number: 80
